/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
  File "examples/test.py", line 303, in <module>
    main()
  File "examples/test.py", line 182, in main
    main_worker(args)
  File "examples/test.py", line 219, in main_worker
    dict_f = extract_features(model, train_extract_loader, pitts_train,
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 55, in extract_features
    outputs = extract_cnn_feature(model, imgs, vlad, gpu=gpu)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 25, in extract_cnn_feature
    outputs = model(inputs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 570, in forward
    pool_x, x_size, x_nodes = self.SelectRegions(x, self.base_model, self.fastscnn)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 541, in forward
    graph_nodes[img_i] = aa[0]
RuntimeError: The expanded size of the tensor (5) must match the existing size (6) at non-singleton dimension 0.  Target sizes: [5, 512, 30, 40].  Tensor sizes: [6, 512, 30, 40]
Traceback (most recent call last):
  File "examples/test.py", line 303, in <module>
    main()
  File "examples/test.py", line 182, in main
    main_worker(args)
  File "examples/test.py", line 219, in main_worker
    dict_f = extract_features(model, train_extract_loader, pitts_train,
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 55, in extract_features
    outputs = extract_cnn_feature(model, imgs, vlad, gpu=gpu)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 25, in extract_cnn_feature
    outputs = model(inputs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 570, in forward
    pool_x, x_size, x_nodes = self.SelectRegions(x, self.base_model, self.fastscnn)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 541, in forward
    graph_nodes[img_i] = aa[0]
RuntimeError: The expanded size of the tensor (5) must match the existing size (6) at non-singleton dimension 0.  Target sizes: [5, 512, 30, 40].  Tensor sizes: [6, 512, 30, 40]
Traceback (most recent call last):
  File "examples/test.py", line 303, in <module>
    main()
  File "examples/test.py", line 182, in main
    main_worker(args)
  File "examples/test.py", line 219, in main_worker
    dict_f = extract_features(model, train_extract_loader, pitts_train,
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 55, in extract_features
    outputs = extract_cnn_feature(model, imgs, vlad, gpu=gpu)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 25, in extract_cnn_feature
    outputs = model(inputs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 570, in forward
    pool_x, x_size, x_nodes = self.SelectRegions(x, self.base_model, self.fastscnn)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 541, in forward
    graph_nodes[img_i] = aa[0]
RuntimeError: The expanded size of the tensor (5) must match the existing size (6) at non-singleton dimension 0.  Target sizes: [5, 512, 30, 40].  Tensor sizes: [6, 512, 30, 40]
Traceback (most recent call last):
  File "examples/test.py", line 303, in <module>
    main()
  File "examples/test.py", line 182, in main
    main_worker(args)
  File "examples/test.py", line 219, in main_worker
    dict_f = extract_features(model, train_extract_loader, pitts_train,
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 55, in extract_features
    outputs = extract_cnn_feature(model, imgs, vlad, gpu=gpu)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 25, in extract_cnn_feature
    outputs = model(inputs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 570, in forward
    pool_x, x_size, x_nodes = self.SelectRegions(x, self.base_model, self.fastscnn)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 541, in forward
    graph_nodes[img_i] = aa[0]
RuntimeError: The expanded size of the tensor (5) must match the existing size (6) at non-singleton dimension 0.  Target sizes: [5, 512, 30, 40].  Tensor sizes: [6, 512, 30, 40]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 920508) of binary: /home/m.maqboolbhutta/.conda/envs/openibl3/bin/python
Traceback (most recent call last):
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/test.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-09-24_09:13:01
  host      : c0906a-s23.ufhpc
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 920509)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-09-24_09:13:01
  host      : c0906a-s23.ufhpc
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 920510)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-09-24_09:13:01
  host      : c0906a-s23.ufhpc
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 920511)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-24_09:13:01
  host      : c0906a-s23.ufhpc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 920508)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
  File "examples/test.py", line 303, in <module>
    main()
  File "examples/test.py", line 182, in main
    main_worker(args)
  File "examples/test.py", line 219, in main_worker
    dict_f = extract_features(model, train_extract_loader, pitts_train,
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 55, in extract_features
    outputs = extract_cnn_feature(model, imgs, vlad, gpu=gpu)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 25, in extract_cnn_feature
    outputs = model(inputs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 570, in forward
    pool_x, x_size, x_nodes = self.SelectRegions(x, self.base_model, self.fastscnn)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 541, in forward
    graph_nodes[img_i] = aa[0]
RuntimeError: The expanded size of the tensor (5) must match the existing size (6) at non-singleton dimension 0.  Target sizes: [5, 512, 30, 40].  Tensor sizes: [6, 512, 30, 40]
Traceback (most recent call last):
  File "examples/test.py", line 303, in <module>
    main()
  File "examples/test.py", line 182, in main
    main_worker(args)
  File "examples/test.py", line 219, in main_worker
    dict_f = extract_features(model, train_extract_loader, pitts_train,
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 55, in extract_features
    outputs = extract_cnn_feature(model, imgs, vlad, gpu=gpu)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 25, in extract_cnn_feature
    outputs = model(inputs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 570, in forward
    pool_x, x_size, x_nodes = self.SelectRegions(x, self.base_model, self.fastscnn)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 541, in forward
    graph_nodes[img_i] = aa[0]
RuntimeError: The expanded size of the tensor (5) must match the existing size (6) at non-singleton dimension 0.  Target sizes: [5, 512, 30, 40].  Tensor sizes: [6, 512, 30, 40]
Traceback (most recent call last):
  File "examples/test.py", line 303, in <module>
    main()
  File "examples/test.py", line 182, in main
    main_worker(args)
  File "examples/test.py", line 219, in main_worker
    dict_f = extract_features(model, train_extract_loader, pitts_train,
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 55, in extract_features
    outputs = extract_cnn_feature(model, imgs, vlad, gpu=gpu)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 25, in extract_cnn_feature
    outputs = model(inputs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 570, in forward
    pool_x, x_size, x_nodes = self.SelectRegions(x, self.base_model, self.fastscnn)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 541, in forward
    graph_nodes[img_i] = aa[0]
RuntimeError: The expanded size of the tensor (5) must match the existing size (6) at non-singleton dimension 0.  Target sizes: [5, 512, 30, 40].  Tensor sizes: [6, 512, 30, 40]
Traceback (most recent call last):
  File "examples/test.py", line 303, in <module>
    main()
  File "examples/test.py", line 182, in main
    main_worker(args)
  File "examples/test.py", line 219, in main_worker
    dict_f = extract_features(model, train_extract_loader, pitts_train,
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 55, in extract_features
    outputs = extract_cnn_feature(model, imgs, vlad, gpu=gpu)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 25, in extract_cnn_feature
    outputs = model(inputs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 570, in forward
    pool_x, x_size, x_nodes = self.SelectRegions(x, self.base_model, self.fastscnn)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 541, in forward
    graph_nodes[img_i] = aa[0]
RuntimeError: The expanded size of the tensor (5) must match the existing size (6) at non-singleton dimension 0.  Target sizes: [5, 512, 30, 40].  Tensor sizes: [6, 512, 30, 40]
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 923276 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 923277 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 923278 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 923275) of binary: /home/m.maqboolbhutta/.conda/envs/openibl3/bin/python
Traceback (most recent call last):
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/test.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-24_09:13:28
  host      : c0906a-s23.ufhpc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 923275)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
  File "examples/test.py", line 303, in <module>
    main()
  File "examples/test.py", line 182, in main
    main_worker(args)
  File "examples/test.py", line 219, in main_worker
    dict_f = extract_features(model, train_extract_loader, pitts_train,
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 55, in extract_features
    outputs = extract_cnn_feature(model, imgs, vlad, gpu=gpu)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 25, in extract_cnn_feature
    outputs = model(inputs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 570, in forward
    pool_x, x_size, x_nodes = self.SelectRegions(x, self.base_model, self.fastscnn)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 541, in forward
    graph_nodes[img_i] = aa[0]
RuntimeError: The expanded size of the tensor (5) must match the existing size (6) at non-singleton dimension 0.  Target sizes: [5, 512, 30, 40].  Tensor sizes: [6, 512, 30, 40]
Traceback (most recent call last):
  File "examples/test.py", line 303, in <module>
    main()
  File "examples/test.py", line 182, in main
    main_worker(args)
  File "examples/test.py", line 219, in main_worker
    dict_f = extract_features(model, train_extract_loader, pitts_train,
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 55, in extract_features
    outputs = extract_cnn_feature(model, imgs, vlad, gpu=gpu)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 25, in extract_cnn_feature
    outputs = model(inputs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 570, in forward
    pool_x, x_size, x_nodes = self.SelectRegions(x, self.base_model, self.fastscnn)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 541, in forward
    graph_nodes[img_i] = aa[0]
RuntimeError: The expanded size of the tensor (5) must match the existing size (6) at non-singleton dimension 0.  Target sizes: [5, 512, 30, 40].  Tensor sizes: [6, 512, 30, 40]
Traceback (most recent call last):
  File "examples/test.py", line 303, in <module>
    main()
  File "examples/test.py", line 182, in main
    main_worker(args)
  File "examples/test.py", line 219, in main_worker
    dict_f = extract_features(model, train_extract_loader, pitts_train,
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 55, in extract_features
    outputs = extract_cnn_feature(model, imgs, vlad, gpu=gpu)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 25, in extract_cnn_feature
    outputs = model(inputs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 570, in forward
    pool_x, x_size, x_nodes = self.SelectRegions(x, self.base_model, self.fastscnn)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 541, in forward
    graph_nodes[img_i] = aa[0]
RuntimeError: The expanded size of the tensor (5) must match the existing size (6) at non-singleton dimension 0.  Target sizes: [5, 512, 30, 40].  Tensor sizes: [6, 512, 30, 40]
Traceback (most recent call last):
  File "examples/test.py", line 303, in <module>
    main()
  File "examples/test.py", line 182, in main
    main_worker(args)
  File "examples/test.py", line 219, in main_worker
    dict_f = extract_features(model, train_extract_loader, pitts_train,
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 55, in extract_features
    outputs = extract_cnn_feature(model, imgs, vlad, gpu=gpu)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 25, in extract_cnn_feature
    outputs = model(inputs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 570, in forward
    pool_x, x_size, x_nodes = self.SelectRegions(x, self.base_model, self.fastscnn)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 541, in forward
    graph_nodes[img_i] = aa[0]
RuntimeError: The expanded size of the tensor (5) must match the existing size (6) at non-singleton dimension 0.  Target sizes: [5, 512, 30, 40].  Tensor sizes: [6, 512, 30, 40]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 927086) of binary: /home/m.maqboolbhutta/.conda/envs/openibl3/bin/python
Traceback (most recent call last):
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/test.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-09-24_09:14:00
  host      : c0906a-s23.ufhpc
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 927088)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-09-24_09:14:00
  host      : c0906a-s23.ufhpc
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 927092)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-09-24_09:14:00
  host      : c0906a-s23.ufhpc
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 927093)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-24_09:14:00
  host      : c0906a-s23.ufhpc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 927086)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
  File "examples/test.py", line 303, in <module>
    main()
  File "examples/test.py", line 182, in main
    main_worker(args)
  File "examples/test.py", line 219, in main_worker
    dict_f = extract_features(model, train_extract_loader, pitts_train,
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 55, in extract_features
    outputs = extract_cnn_feature(model, imgs, vlad, gpu=gpu)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 25, in extract_cnn_feature
    outputs = model(inputs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 570, in forward
    pool_x, x_size, x_nodes = self.SelectRegions(x, self.base_model, self.fastscnn)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 541, in forward
    graph_nodes[img_i] = aa[0]
RuntimeError: The expanded size of the tensor (5) must match the existing size (6) at non-singleton dimension 0.  Target sizes: [5, 512, 30, 40].  Tensor sizes: [6, 512, 30, 40]
Traceback (most recent call last):
  File "examples/test.py", line 303, in <module>
    main()
  File "examples/test.py", line 182, in main
    main_worker(args)
  File "examples/test.py", line 219, in main_worker
    dict_f = extract_features(model, train_extract_loader, pitts_train,
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 55, in extract_features
    outputs = extract_cnn_feature(model, imgs, vlad, gpu=gpu)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 25, in extract_cnn_feature
    outputs = model(inputs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 570, in forward
    pool_x, x_size, x_nodes = self.SelectRegions(x, self.base_model, self.fastscnn)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 541, in forward
    graph_nodes[img_i] = aa[0]
RuntimeError: The expanded size of the tensor (5) must match the existing size (6) at non-singleton dimension 0.  Target sizes: [5, 512, 30, 40].  Tensor sizes: [6, 512, 30, 40]
Traceback (most recent call last):
  File "examples/test.py", line 303, in <module>
    main()
  File "examples/test.py", line 182, in main
    main_worker(args)
  File "examples/test.py", line 219, in main_worker
    dict_f = extract_features(model, train_extract_loader, pitts_train,
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 55, in extract_features
    outputs = extract_cnn_feature(model, imgs, vlad, gpu=gpu)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 25, in extract_cnn_feature
    outputs = model(inputs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 570, in forward
    pool_x, x_size, x_nodes = self.SelectRegions(x, self.base_model, self.fastscnn)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 541, in forward
    graph_nodes[img_i] = aa[0]
RuntimeError: The expanded size of the tensor (5) must match the existing size (6) at non-singleton dimension 0.  Target sizes: [5, 512, 30, 40].  Tensor sizes: [6, 512, 30, 40]
Traceback (most recent call last):
  File "examples/test.py", line 303, in <module>
    main()
  File "examples/test.py", line 182, in main
    main_worker(args)
  File "examples/test.py", line 219, in main_worker
    dict_f = extract_features(model, train_extract_loader, pitts_train,
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 55, in extract_features
    outputs = extract_cnn_feature(model, imgs, vlad, gpu=gpu)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 25, in extract_cnn_feature
    outputs = model(inputs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 570, in forward
    pool_x, x_size, x_nodes = self.SelectRegions(x, self.base_model, self.fastscnn)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 541, in forward
    graph_nodes[img_i] = aa[0]
RuntimeError: The expanded size of the tensor (5) must match the existing size (6) at non-singleton dimension 0.  Target sizes: [5, 512, 30, 40].  Tensor sizes: [6, 512, 30, 40]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 931072) of binary: /home/m.maqboolbhutta/.conda/envs/openibl3/bin/python
Traceback (most recent call last):
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/test.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-09-24_09:14:32
  host      : c0906a-s23.ufhpc
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 931073)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-09-24_09:14:32
  host      : c0906a-s23.ufhpc
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 931074)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-09-24_09:14:32
  host      : c0906a-s23.ufhpc
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 931075)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-24_09:14:32
  host      : c0906a-s23.ufhpc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 931072)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
  File "examples/test.py", line 303, in <module>
    main()
  File "examples/test.py", line 182, in main
    main_worker(args)
  File "examples/test.py", line 219, in main_worker
    dict_f = extract_features(model, train_extract_loader, pitts_train,
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 55, in extract_features
    outputs = extract_cnn_feature(model, imgs, vlad, gpu=gpu)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 25, in extract_cnn_feature
    outputs = model(inputs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 570, in forward
    pool_x, x_size, x_nodes = self.SelectRegions(x, self.base_model, self.fastscnn)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 541, in forward
    graph_nodes[img_i] = aa[0]
RuntimeError: The expanded size of the tensor (5) must match the existing size (6) at non-singleton dimension 0.  Target sizes: [5, 512, 30, 40].  Tensor sizes: [6, 512, 30, 40]
Traceback (most recent call last):
  File "examples/test.py", line 303, in <module>
    main()
  File "examples/test.py", line 182, in main
    main_worker(args)
  File "examples/test.py", line 219, in main_worker
    dict_f = extract_features(model, train_extract_loader, pitts_train,
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 55, in extract_features
    outputs = extract_cnn_feature(model, imgs, vlad, gpu=gpu)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 25, in extract_cnn_feature
    outputs = model(inputs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 570, in forward
    pool_x, x_size, x_nodes = self.SelectRegions(x, self.base_model, self.fastscnn)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 541, in forward
    graph_nodes[img_i] = aa[0]
RuntimeError: The expanded size of the tensor (5) must match the existing size (6) at non-singleton dimension 0.  Target sizes: [5, 512, 30, 40].  Tensor sizes: [6, 512, 30, 40]
Traceback (most recent call last):
  File "examples/test.py", line 303, in <module>
    main()
  File "examples/test.py", line 182, in main
    main_worker(args)
  File "examples/test.py", line 219, in main_worker
    dict_f = extract_features(model, train_extract_loader, pitts_train,
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 55, in extract_features
    outputs = extract_cnn_feature(model, imgs, vlad, gpu=gpu)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 25, in extract_cnn_feature
    outputs = model(inputs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 570, in forward
    pool_x, x_size, x_nodes = self.SelectRegions(x, self.base_model, self.fastscnn)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 541, in forward
    graph_nodes[img_i] = aa[0]
RuntimeError: The expanded size of the tensor (5) must match the existing size (6) at non-singleton dimension 0.  Target sizes: [5, 512, 30, 40].  Tensor sizes: [6, 512, 30, 40]
Traceback (most recent call last):
  File "examples/test.py", line 303, in <module>
    main()
  File "examples/test.py", line 182, in main
    main_worker(args)
  File "examples/test.py", line 219, in main_worker
    dict_f = extract_features(model, train_extract_loader, pitts_train,
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 55, in extract_features
    outputs = extract_cnn_feature(model, imgs, vlad, gpu=gpu)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 25, in extract_cnn_feature
    outputs = model(inputs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 570, in forward
    pool_x, x_size, x_nodes = self.SelectRegions(x, self.base_model, self.fastscnn)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 541, in forward
    graph_nodes[img_i] = aa[0]
RuntimeError: The expanded size of the tensor (5) must match the existing size (6) at non-singleton dimension 0.  Target sizes: [5, 512, 30, 40].  Tensor sizes: [6, 512, 30, 40]
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 935054 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 935052) of binary: /home/m.maqboolbhutta/.conda/envs/openibl3/bin/python
Traceback (most recent call last):
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/test.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-09-24_09:14:58
  host      : c0906a-s23.ufhpc
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 935053)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-09-24_09:14:58
  host      : c0906a-s23.ufhpc
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 935055)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-24_09:14:58
  host      : c0906a-s23.ufhpc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 935052)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
  File "examples/test.py", line 303, in <module>
    main()
  File "examples/test.py", line 182, in main
    main_worker(args)
  File "examples/test.py", line 219, in main_worker
    dict_f = extract_features(model, train_extract_loader, pitts_train,
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 55, in extract_features
    outputs = extract_cnn_feature(model, imgs, vlad, gpu=gpu)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 25, in extract_cnn_feature
    outputs = model(inputs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 570, in forward
    pool_x, x_size, x_nodes = self.SelectRegions(x, self.base_model, self.fastscnn)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 541, in forward
    graph_nodes[img_i] = aa[0]
RuntimeError: The expanded size of the tensor (5) must match the existing size (6) at non-singleton dimension 0.  Target sizes: [5, 512, 30, 40].  Tensor sizes: [6, 512, 30, 40]
Traceback (most recent call last):
  File "examples/test.py", line 303, in <module>
    main()
  File "examples/test.py", line 182, in main
    main_worker(args)
  File "examples/test.py", line 219, in main_worker
    dict_f = extract_features(model, train_extract_loader, pitts_train,
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 55, in extract_features
    outputs = extract_cnn_feature(model, imgs, vlad, gpu=gpu)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 25, in extract_cnn_feature
    outputs = model(inputs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 570, in forward
    pool_x, x_size, x_nodes = self.SelectRegions(x, self.base_model, self.fastscnn)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 541, in forward
    graph_nodes[img_i] = aa[0]
RuntimeError: The expanded size of the tensor (5) must match the existing size (6) at non-singleton dimension 0.  Target sizes: [5, 512, 30, 40].  Tensor sizes: [6, 512, 30, 40]
Traceback (most recent call last):
  File "examples/test.py", line 303, in <module>
    main()
  File "examples/test.py", line 182, in main
    main_worker(args)
  File "examples/test.py", line 219, in main_worker
    dict_f = extract_features(model, train_extract_loader, pitts_train,
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 55, in extract_features
    outputs = extract_cnn_feature(model, imgs, vlad, gpu=gpu)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 25, in extract_cnn_feature
    outputs = model(inputs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 570, in forward
    pool_x, x_size, x_nodes = self.SelectRegions(x, self.base_model, self.fastscnn)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 541, in forward
    graph_nodes[img_i] = aa[0]
RuntimeError: The expanded size of the tensor (5) must match the existing size (6) at non-singleton dimension 0.  Target sizes: [5, 512, 30, 40].  Tensor sizes: [6, 512, 30, 40]
Traceback (most recent call last):
  File "examples/test.py", line 303, in <module>
    main()
  File "examples/test.py", line 182, in main
    main_worker(args)
  File "examples/test.py", line 219, in main_worker
    dict_f = extract_features(model, train_extract_loader, pitts_train,
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 55, in extract_features
    outputs = extract_cnn_feature(model, imgs, vlad, gpu=gpu)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/evaluators.py", line 25, in extract_cnn_feature
    outputs = model(inputs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 570, in forward
    pool_x, x_size, x_nodes = self.SelectRegions(x, self.base_model, self.fastscnn)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/hmedeiros/m.maqboolbhutta/codes/openibl3/examples/ibl/models/netvlad.py", line 541, in forward
    graph_nodes[img_i] = aa[0]
RuntimeError: The expanded size of the tensor (5) must match the existing size (6) at non-singleton dimension 0.  Target sizes: [5, 512, 30, 40].  Tensor sizes: [6, 512, 30, 40]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 938705) of binary: /home/m.maqboolbhutta/.conda/envs/openibl3/bin/python
Traceback (most recent call last):
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/test.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-09-24_09:15:31
  host      : c0906a-s23.ufhpc
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 938706)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-09-24_09:15:31
  host      : c0906a-s23.ufhpc
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 938707)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-09-24_09:15:31
  host      : c0906a-s23.ufhpc
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 938708)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-24_09:15:31
  host      : c0906a-s23.ufhpc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 938705)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/home/m.maqboolbhutta/.conda/envs/openibl3/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
slurmstepd: error: *** JOB 45389857 ON c0906a-s23 CANCELLED AT 2024-09-24T09:15:39 ***
